# Generated by Django 3.0.7 on 2020-06-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitem',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterIndexTogether(
            name='shopitem',
            index_together={('id', 'slug')},
        ),
    ]
