# Generated by Django 3.0.7 on 2020-06-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200612_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='picture',
            field=models.ImageField(default='index.jpeg', upload_to=''),
        ),
    ]
