# Generated by Django 3.0.7 on 2020-07-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_galleryitem_gallerypicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypicture',
            name='gallery_item',
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.DeleteModel(
            name='GalleryPicture',
        ),
    ]
