# Generated by Django 3.0.7 on 2020-07-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200713_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='primary_picture',
            field=models.ImageField(default='index.jpeg', upload_to=''),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='slug',
            field=models.SlugField(default='ok', max_length=200),
            preserve_default=False,
        ),
    ]
