# Generated by Django 3.0.7 on 2020-09-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_deliveryoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryoption',
            options={'ordering': ('price',)},
        ),
    ]
