# Generated by Django 3.0.7 on 2020-09-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200906_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='description',
            field=models.CharField(default='**Awesome** picture, and *model*.', max_length=1000),
        ),
    ]
