# Generated by Django 3.0.7 on 2020-09-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200910_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ('-date_added',)},
        ),
    ]
