# Generated by Django 3.0.7 on 2020-09-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='s_name',
            new_name='second_name',
        ),
    ]
