# Generated by Django 3.0.7 on 2020-09-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200906_1456'),
        ('orders', '0003_auto_20200906_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='store.DeliveryOption'),
        ),
    ]
